load("//tools:defs.bzl", "bzl_library")

package(licenses = ["notice"])

bzl_library(
    name = "defs_bzl",
    srcs = ["defs.bzl"],
    parse_tests = False,
    visibility = ["//visibility:private"],
)
